#!/usr/bin/env bash
# PreToolUse guard (Edit|Write|MultiEdit): block hand-edits to drizzle-generated SQL.
set -euo pipefail

input=$(cat)
file=$(jq -r '.tool_input.file_path // empty' <<<"$input")
[[ -z "$file" ]] && exit 0

case "$file" in
  */packages/adapters/store-postgres/drizzle/*)
    cat >&2 <<'MSG'
BLOCKED: files under packages/adapters/store-postgres/drizzle/ are generated by
drizzle-kit and must never be hand-edited. Instead:
  1. Edit packages/adapters/store-postgres/src/schema.ts
  2. Run: pnpm --filter @cw/adapter-store-postgres generate
  3. Commit the newly generated SQL + drizzle/meta/ together with schema.ts
MSG
    exit 2
    ;;
esac
exit 0
