/**
 * cw-codegen — emit TypeScript field shapes from a content model.
 *
 *   # From a live Management/Preview API (any token with preview read):
 *   cw-codegen --url https://cms.example.com --space s1 --environment main \
 *     --token $CMA_TOKEN --out src/generated/content-types.ts
 *
 *   # From an exported JSON file ({ items: [...] } or a bare array):
 *   cw-codegen --input content-types.json > content-types.ts
 */

import { readFile, writeFile } from 'node:fs/promises';
import { generateTypes } from './generate.js';
import type { ContentTypeInput } from './generate.js';

export interface CliArgs {
  readonly url?: string;
  readonly space?: string;
  readonly environment?: string;
  readonly token?: string;
  readonly input?: string;
  readonly out?: string;
  readonly help?: boolean;
}

const FLAGS = new Set(['url', 'space', 'environment', 'token', 'input', 'out']);

/** Parses `--flag value` pairs; throws on unknown flags or missing values. */
export function parseArgs(argv: readonly string[]): CliArgs {
  const args: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    const raw = argv[i] as string;
    if (raw === '--help' || raw === '-h') {
      args.help = true;
      continue;
    }
    if (!raw.startsWith('--')) throw new Error(`Unexpected argument: ${raw}`);
    const flag = raw.slice(2);
    if (!FLAGS.has(flag)) throw new Error(`Unknown flag: ${raw}`);
    const value = argv[i + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new Error(`Missing value for ${raw}`);
    }
    args[flag] = value;
    i++;
  }
  return args as CliArgs;
}

const USAGE = `Usage:
  cw-codegen --url <baseUrl> --space <id> --environment <id> --token <token> [--out <file>]
  cw-codegen --input <content-types.json> [--out <file>]

Reads the space's content types (live API or exported JSON) and emits a
TypeScript module of field shapes for the @cw SDKs. Writes to stdout unless
--out is given.`;

/** Loads content types from the configured source. */
export async function loadContentTypes(
  args: CliArgs,
  fetchImpl: typeof fetch = globalThis.fetch,
): Promise<ContentTypeInput[]> {
  if (args.input) {
    const parsed = JSON.parse(await readFile(args.input, 'utf8')) as
      | { items?: ContentTypeInput[] }
      | ContentTypeInput[];
    return Array.isArray(parsed) ? parsed : (parsed.items ?? []);
  }
  if (!args.url || !args.space || !args.environment || !args.token) {
    throw new Error(`--url, --space, --environment, and --token are all required\n\n${USAGE}`);
  }
  const base = args.url.replace(/\/$/, '');
  const url = `${base}/spaces/${encodeURIComponent(args.space)}/environments/${encodeURIComponent(
    args.environment,
  )}/content-types`;
  const res = await fetchImpl(url, { headers: { authorization: `Bearer ${args.token}` } });
  if (!res.ok) throw new Error(`Fetching content types failed: ${res.status} ${url}`);
  const body = (await res.json()) as { items?: ContentTypeInput[] };
  return body.items ?? [];
}

export async function main(argv: readonly string[]): Promise<void> {
  const args = parseArgs(argv);
  if (args.help) {
    console.log(USAGE);
    return;
  }
  const contentTypes = await loadContentTypes(args);
  const source = generateTypes(contentTypes, {
    banner: args.input
      ? `Generated by @cw/sdk-codegen from ${args.input}. Do not edit by hand.`
      : `Generated by @cw/sdk-codegen from ${args.space}/${args.environment}. Do not edit by hand.`,
  });
  if (args.out) {
    await writeFile(args.out, source, 'utf8');
    console.error(`Wrote ${contentTypes.length} content type(s) to ${args.out}`);
  } else {
    console.log(source);
  }
}
