/**
 * Pure generator: content-type definitions in → TypeScript source out.
 * The emitted module gives every SDK a typed field shape to plug into their
 * `F extends Fields` generics: `client.getEntry<ArticleFields>(id)`.
 */

/** The subset of a content-type definition the generator reads. Matches the
 *  Management API's `GET .../content-types` items (extra keys are ignored). */
export interface ContentTypeInput {
  readonly apiId: string;
  readonly name?: string;
  readonly fields: readonly FieldInput[];
}

export interface FieldInput {
  readonly apiId: string;
  readonly name?: string;
  readonly type: string;
  readonly localized?: boolean;
  readonly required?: boolean;
  readonly validations?: {
    readonly in?: readonly (string | number)[];
    readonly linkContentTypes?: readonly string[];
  };
  readonly linkType?: 'Entry' | 'Asset';
  readonly items?: {
    readonly type: string;
    readonly linkType?: 'Entry' | 'Asset';
    readonly validations?: { readonly in?: readonly (string | number)[] };
  };
}

export interface GenerateOptions {
  /** Header comment noting provenance (defaults to a generic banner). */
  readonly banner?: string;
}

/** Shared helper types emitted once at the top of every generated module. */
const PRELUDE = `/** A reference to another entry. Delivery may embed the linked entry in place
 *  of this shape when \`include\` depth covers it. */
export interface EntryLink {
  id: string;
  linkType: 'Entry';
}

/** A reference to an asset. */
export interface AssetLink {
  id: string;
  linkType: 'Asset';
}

export interface RichTextMark {
  type: string;
}

export interface RichTextNode {
  nodeType: string;
  content?: RichTextNode[];
  value?: string;
  marks?: RichTextMark[];
  data?: { target?: EntryLink | AssetLink } & Record<string, unknown>;
}

export interface RichTextDocument {
  nodeType: 'document';
  content: RichTextNode[];
  data?: Record<string, unknown>;
}

export interface Location {
  lat: number;
  lon: number;
}

/** Management (draft) values are keyed by locale code. */
export type Localized<T> = Record<string, T>;
`;

/** Generates a self-contained TypeScript module from content-type definitions. */
export function generateTypes(
  contentTypes: readonly ContentTypeInput[],
  opts: GenerateOptions = {},
): string {
  const banner =
    opts.banner ?? 'Generated by @cw/sdk-codegen from your content model. Do not edit by hand.';
  const names = assignTypeNames(contentTypes);
  const sections: string[] = [`// ${banner}\n`, PRELUDE];

  for (const ct of contentTypes) {
    const typeName = names.get(ct.apiId) as string;
    sections.push(renderContentType(ct, typeName));
  }

  if (contentTypes.length > 0) {
    const ids = contentTypes.map((ct) => literal(ct.apiId)).join(' | ');
    const deliveryRows = contentTypes
      .map((ct) => `  ${propertyKey(ct.apiId)}: ${names.get(ct.apiId)}Fields;`)
      .join('\n');
    const draftRows = contentTypes
      .map((ct) => `  ${propertyKey(ct.apiId)}: ${names.get(ct.apiId)}DraftFields;`)
      .join('\n');
    sections.push(
      `export type ContentTypeApiId = ${ids};\n`,
      `/** Delivery field shapes by content type apiId. */\nexport interface FieldsByContentType {\n${deliveryRows}\n}\n`,
      `/** Management (locale-keyed) field shapes by content type apiId. */\nexport interface DraftFieldsByContentType {\n${draftRows}\n}\n`,
    );
  }

  return sections.join('\n');
}

function renderContentType(ct: ContentTypeInput, typeName: string): string {
  const label = escapeComment(ct.name ? `${ct.name} (\`${ct.apiId}\`)` : `\`${ct.apiId}\``);
  const delivery: string[] = [];
  const draft: string[] = [];

  for (const field of ct.fields) {
    const valueType = fieldValueType(field);
    const key = propertyKey(field.apiId);
    const opt = field.required ? '' : '?';
    const comment = fieldComment(field);
    delivery.push(`${comment}  ${key}${opt}: ${valueType};`);
    draft.push(`${comment}  ${key}${opt}: Localized<${valueType}>;`);
  }

  // Type aliases, not interfaces: aliases get an implicit index signature, so
  // they satisfy the SDKs' `F extends Record<string, unknown>` generics.
  return [
    `/** ${label} — Delivery shape (locale-flattened; request with \`?locale=\`). */\nexport type ${typeName}Fields = {\n${delivery.join('\n')}\n};\n`,
    `/** ${label} — Management shape (locale-keyed draft values). */\nexport type ${typeName}DraftFields = {\n${draft.join('\n')}\n};\n`,
  ].join('\n');
}

/** Maps a field definition to the TypeScript type of a single (locale-resolved) value. */
export function fieldValueType(field: FieldInput): string {
  // `in` validations narrow to a literal union only where the domain actually
  // enforces them (Symbol/Text/Integer/Number) — elsewhere stored values may
  // legally fall outside the list, so the wider type is the truthful one.
  switch (field.type) {
    case 'Symbol':
    case 'Text':
      return literalUnion(field.validations?.in) ?? 'string';
    case 'Date':
      return 'string';
    case 'Integer':
    case 'Number':
      return literalUnion(field.validations?.in) ?? 'number';
    case 'Boolean':
      return 'boolean';
    case 'Location':
      return 'Location';
    case 'JSON':
      return 'Record<string, unknown>';
    case 'RichText':
      return 'RichTextDocument';
    case 'Link':
      return field.linkType === 'Asset' ? 'AssetLink' : 'EntryLink';
    case 'Array': {
      const items = field.items;
      if (items?.type === 'Link') {
        return items.linkType === 'Asset' ? 'AssetLink[]' : 'EntryLink[]';
      }
      return 'string[]';
    }
    default:
      return 'unknown';
  }
}

/** An `in` validation becomes a literal union (`'a' | 'b'`); absent → null. */
function literalUnion(values: readonly (string | number)[] | undefined): string | null {
  if (!values || values.length === 0) return null;
  return values.map(literal).join(' | ');
}

function literal(value: string | number): string {
  return typeof value === 'number' ? String(value) : `'${escapeString(value)}'`;
}

/** Escapes a value for a single-quoted TS string literal. */
function escapeString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Quotes a property key unless it is already a valid identifier. */
function propertyKey(apiId: string): string {
  return IDENTIFIER.test(apiId) ? apiId : `'${escapeString(apiId)}'`;
}

function fieldComment(field: FieldInput): string {
  const notes: string[] = [];
  if (field.name && field.name !== field.apiId) notes.push(escapeComment(field.name));
  if (field.localized) notes.push('localized');
  if (field.linkType || field.items?.linkType) {
    const allowed = field.validations?.linkContentTypes;
    if (allowed?.length) notes.push(escapeComment(`links: ${allowed.join(', ')}`));
  }
  return notes.length ? `  /** ${notes.join(' — ')} */\n` : '';
}

function escapeComment(text: string): string {
  return text.replace(/\*\//g, '*\\/');
}

/** apiId → PascalCase type name, deduplicated across the model. */
function assignTypeNames(contentTypes: readonly ContentTypeInput[]): Map<string, string> {
  const names = new Map<string, string>();
  const taken = new Set<string>();
  for (const ct of contentTypes) {
    let name = pascalCase(ct.apiId);
    if (!name) name = 'ContentType';
    let candidate = name;
    let n = 2;
    while (taken.has(candidate)) candidate = `${name}${n++}`;
    taken.add(candidate);
    names.set(ct.apiId, candidate);
  }
  return names;
}

function pascalCase(apiId: string): string {
  return apiId
    .replace(/^[0-9]+/, '')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}
